.TH "trabalhoPOO_27967.Client" 3 "Version v 1.0" "LESI_TP_POO_27967" \" -*- nroff -*-
.ad l
.nh
.SH NAME
trabalhoPOO_27967.Client \- Purpose: Definition of Client and methods to deal with Client operations\&. Created by: Jose Alves a27967 Created on: 10/29/2024 4:23:56 PM\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClient\fP ()"
.br
.RI "The default Constructor\&. "
.ti -1c
.RI "\fBClient\fP (string n, string c)"
.br
.RI "Constructor to use when a name and a contact are given\&. "
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Redefine the ToString Function to show a client's info\&. "
.ti -1c
.RI "override bool \fBEquals\fP (object obj)"
.br
.RI "Redefine the Equals operator to verify if a client matches the other\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBoperator==\fP (\fBClient\fP cli1, \fBClient\fP cli2)"
.br
.RI "Redefinition of the == operator\&. "
.ti -1c
.RI "static bool \fBoperator!=\fP (\fBClient\fP cli1, \fBClient\fP cli2)"
.br
.RI "Redefinition of the != operator\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBClientID\fP\fC [get, set]\fP"
.br
.RI "Property that sets or returns the ID of a client\&. "
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.RI "Property that sets or returns the Name of a client\&. "
.ti -1c
.RI "string \fBContact\fP\fC [get, set]\fP"
.br
.RI "Property that sets or returns the Contact of a client\&. "
.ti -1c
.RI "static int \fBClientCount\fP\fC [get, set]\fP"
.br
.RI "Property that sets or returns the amount of clients\&. "
.in -1c
.SH "Detailed Description"
.PP 
Purpose: Definition of Client and methods to deal with Client operations\&. Created by: Jose Alves a27967 Created on: 10/29/2024 4:23:56 PM\&. 


.PP
Definition at line \fB23\fP of file \fBClient\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "trabalhoPOO_27967\&.Client\&.Client ()"

.PP
The default Constructor\&. 
.PP
Definition at line \fB39\fP of file \fBClient\&.cs\fP\&.
.SS "trabalhoPOO_27967\&.Client\&.Client (string n, string c)"

.PP
Constructor to use when a name and a contact are given\&. 
.PP
\fBParameters\fP
.RS 4
\fIn\fP 
.br
\fIc\fP 
.RE
.PP

.PP
Definition at line \fB51\fP of file \fBClient\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool trabalhoPOO_27967\&.Client\&.Equals (object obj)"

.PP
Redefine the Equals operator to verify if a client matches the other\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP
Veriffies if the object given is null\&.
.PP
Casts the object to be Client\&.
.PP
Definition at line \fB131\fP of file \fBClient\&.cs\fP\&.
.SS "static bool trabalhoPOO_27967\&.Client\&.operator!= (\fBClient\fP cli1, \fBClient\fP cli2)\fC [static]\fP"

.PP
Redefinition of the != operator\&. 
.PP
\fBParameters\fP
.RS 4
\fIcli1\fP 
.br
\fIcli2\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB161\fP of file \fBClient\&.cs\fP\&.
.SS "static bool trabalhoPOO_27967\&.Client\&.operator== (\fBClient\fP cli1, \fBClient\fP cli2)\fC [static]\fP"

.PP
Redefinition of the == operator\&. 
.PP
\fBParameters\fP
.RS 4
\fIcli1\fP 
.br
\fIcli2\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB150\fP of file \fBClient\&.cs\fP\&.
.SS "override string trabalhoPOO_27967\&.Client\&.ToString ()"

.PP
Redefine the ToString Function to show a client's info\&. 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line \fB116\fP of file \fBClient\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int trabalhoPOO_27967\&.Client\&.ClientCount\fC [static]\fP, \fC [get]\fP, \fC [set]\fP"

.PP
Property that sets or returns the amount of clients\&. 
.PP
Definition at line \fB100\fP of file \fBClient\&.cs\fP\&.
.SS "int trabalhoPOO_27967\&.Client\&.ClientID\fC [get]\fP, \fC [set]\fP"

.PP
Property that sets or returns the ID of a client\&. 
.PP
Definition at line \fB65\fP of file \fBClient\&.cs\fP\&.
.SS "string trabalhoPOO_27967\&.Client\&.Contact\fC [get]\fP, \fC [set]\fP"

.PP
Property that sets or returns the Contact of a client\&. 
.PP
Definition at line \fB83\fP of file \fBClient\&.cs\fP\&.
.SS "string trabalhoPOO_27967\&.Client\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Property that sets or returns the Name of a client\&. 
.PP
Definition at line \fB74\fP of file \fBClient\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LESI_TP_POO_27967 from the source code\&.
