.TH "trabalhoPOO_27967.Clients" 3 "Version v 1.0" "LESI_TP_POO_27967" \" -*- nroff -*-
.ad l
.nh
.SH NAME
trabalhoPOO_27967.Clients \- Purpose: Class with the definition and methods to manage a list of clients\&. Created by: Jose Alves a27967 Created on: 11/12/2024 9:25:28 PM\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClients\fP ()"
.br
.RI "The default Constructor\&. "
.ti -1c
.RI "bool \fBAddClient\fP (\fBClient\fP cli)"
.br
.RI "Method to add a client to the store's client list\&. "
.ti -1c
.RI "bool \fBRemoveClient\fP (\fBClient\fP cli)"
.br
.RI "Method to remove a client from the store's client list\&. "
.ti -1c
.RI "bool \fBExistClient\fP (int id)"
.br
.RI "Method to check if a client is listed on a clients' list\&. "
.ti -1c
.RI "\fBClient\fP \fBGetClient\fP (int id)"
.br
.RI "Method used to get a client from a clients' list\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "List< \fBClient\fP > \fBClientList\fP\fC [get, set]\fP"
.br
.RI "Property used to get and set the client list\&. "
.in -1c
.SH "Detailed Description"
.PP 
Purpose: Class with the definition and methods to manage a list of clients\&. Created by: Jose Alves a27967 Created on: 11/12/2024 9:25:28 PM\&. 


.PP
Definition at line \fB21\fP of file \fBClients\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "trabalhoPOO_27967\&.Clients\&.Clients ()"

.PP
The default Constructor\&. 
.PP
Definition at line \fB34\fP of file \fBClients\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool trabalhoPOO_27967\&.Clients\&.AddClient (\fBClient\fP cli)"

.PP
Method to add a client to the store's client list\&. 
.PP
\fBParameters\fP
.RS 4
\fIcli\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB65\fP of file \fBClients\&.cs\fP\&.
.SS "bool trabalhoPOO_27967\&.Clients\&.ExistClient (int id)"

.PP
Method to check if a client is listed on a clients' list\&. 
.PP
\fBParameters\fP
.RS 4
\fIid\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB95\fP of file \fBClients\&.cs\fP\&.
.SS "\fBClient\fP trabalhoPOO_27967\&.Clients\&.GetClient (int id)"

.PP
Method used to get a client from a clients' list\&. 
.PP
\fBParameters\fP
.RS 4
\fIid\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB112\fP of file \fBClients\&.cs\fP\&.
.SS "bool trabalhoPOO_27967\&.Clients\&.RemoveClient (\fBClient\fP cli)"

.PP
Method to remove a client from the store's client list\&. 
.PP
\fBParameters\fP
.RS 4
\fIcli\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB77\fP of file \fBClients\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "List<\fBClient\fP> trabalhoPOO_27967\&.Clients\&.ClientList\fC [get]\fP, \fC [set]\fP"

.PP
Property used to get and set the client list\&. 
.PP
Definition at line \fB47\fP of file \fBClients\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LESI_TP_POO_27967 from the source code\&.
