.TH "D:/Aulas/POO/TP_POO_27967/trabalhoPOO_27967/obj/Debug/.NETFramework,Version=v4.7.2.AssemblyAttributes.cs" 3 "Version v 1.0" "LESI_TP_POO_27967" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Aulas/POO/TP_POO_27967/trabalhoPOO_27967/obj/Debug/.NETFramework,Version=v4.7.2.AssemblyAttributes.cs
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for LESI_TP_POO_27967 from the source code\&.
