.TH "D:/Aulas/POO/TP_POO_27967/trabalhoPOO_27967 Directory Reference" 3 "Version v 1.0" "LESI_TP_POO_27967" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Aulas/POO/TP_POO_27967/trabalhoPOO_27967 Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBCampaign\fP"
.br
.ti -1c
.RI "directory \fBCategory\fP"
.br
.ti -1c
.RI "directory \fBClient\fP"
.br
.ti -1c
.RI "directory \fBInterface\fP"
.br
.ti -1c
.RI "directory \fBMake\fP"
.br
.ti -1c
.RI "directory \fBobj\fP"
.br
.ti -1c
.RI "directory \fBProduct\fP"
.br
.ti -1c
.RI "directory \fBProperties\fP"
.br
.ti -1c
.RI "directory \fBSale\fP"
.br
.ti -1c
.RI "directory \fBStore\fP"
.br
.ti -1c
.RI "directory \fBWarranty\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBestSale\&.cs\fP"
.br
.in -1c
