.TH "D:/Aulas/POO/TP_POO_27967/trabalhoPOO_27967/Interface/IListManagement.cs" 3 "Version v 1.0" "LESI_TP_POO_27967" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Aulas/POO/TP_POO_27967/trabalhoPOO_27967/Interface/IListManagement.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBtrabalhoPOO_27967\&.Interface\&.IListManagement\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtrabalhoPOO_27967\fP"
.br
.ti -1c
.RI "namespace \fBtrabalhoPOO_27967\&.Interface\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LESI_TP_POO_27967 from the source code\&.
