.TH "D:/Aulas/POO/TP_POO_27967/trabalhoPOO_27967/Product/Product.cs" 3 "Version v 1.0" "LESI_TP_POO_27967" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Aulas/POO/TP_POO_27967/trabalhoPOO_27967/Product/Product.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtrabalhoPOO_27967\&.Product\fP"
.br
.RI "Purpose: Definition of product and methods to deal with product operations\&. Created by: Jose Alves a27967 Created on: 11/2/2024 4:40:12 PM\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtrabalhoPOO_27967\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LESI_TP_POO_27967 from the source code\&.
