.TH "trabalhoPOO_27967.Warranties" 3 "Version v 1.0" "LESI_TP_POO_27967" \" -*- nroff -*-
.ad l
.nh
.SH NAME
trabalhoPOO_27967.Warranties \- Purpose:This file has the definition and methods to work with the plurality of Warranty\&. Created by: Jose Alves a27967 Created on: 11/14/2024 4:20:11 PM\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWarranties\fP ()"
.br
.RI "The default Constructor\&. "
.ti -1c
.RI "\fBWarranties\fP (List< \fBWarranty\fP > warrants)"
.br
.RI "The constructor to use when a list of Warranties is given\&. "
.ti -1c
.RI "bool \fBAddWarranty\fP (\fBWarranty\fP w)"
.br
.ti -1c
.RI "bool \fBRemoveWarranty\fP (\fBWarranty\fP w)"
.br
.RI "Method used to remove a warranty from a list of warranties\&. "
.ti -1c
.RI "bool \fBExistWarranty\fP (string id)"
.br
.RI "Method used to confirm if a campaign exists on a list of campaigns\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "List< \fBWarranty\fP > \fBWarrants\fP\fC [get, set]\fP"
.br
.RI "Property used to get and set the list of warranties\&. "
.in -1c
.SH "Detailed Description"
.PP 
Purpose:This file has the definition and methods to work with the plurality of Warranty\&. Created by: Jose Alves a27967 Created on: 11/14/2024 4:20:11 PM\&. 


.PP
Definition at line \fB21\fP of file \fBWarranties\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "trabalhoPOO_27967\&.Warranties\&.Warranties ()"

.PP
The default Constructor\&. 
.PP
Definition at line \fB34\fP of file \fBWarranties\&.cs\fP\&.
.SS "trabalhoPOO_27967\&.Warranties\&.Warranties (List< \fBWarranty\fP > warrants)"

.PP
The constructor to use when a list of Warranties is given\&. 
.PP
\fBParameters\fP
.RS 4
\fIwarrants\fP 
.RE
.PP

.PP
Definition at line \fB43\fP of file \fBWarranties\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool trabalhoPOO_27967\&.Warranties\&.AddWarranty (\fBWarranty\fP w)"
Method used to add a warranty to a list of warranties\&.
.PP
\fBParameters\fP
.RS 4
\fIc\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB74\fP of file \fBWarranties\&.cs\fP\&.
.SS "bool trabalhoPOO_27967\&.Warranties\&.ExistWarranty (string id)"

.PP
Method used to confirm if a campaign exists on a list of campaigns\&. 
.PP
\fBParameters\fP
.RS 4
\fIid\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB104\fP of file \fBWarranties\&.cs\fP\&.
.SS "bool trabalhoPOO_27967\&.Warranties\&.RemoveWarranty (\fBWarranty\fP w)"

.PP
Method used to remove a warranty from a list of warranties\&. 
.PP
\fBParameters\fP
.RS 4
\fIcamp\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB86\fP of file \fBWarranties\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "List<\fBWarranty\fP> trabalhoPOO_27967\&.Warranties\&.Warrants\fC [get]\fP, \fC [set]\fP"

.PP
Property used to get and set the list of warranties\&. 
.PP
Definition at line \fB56\fP of file \fBWarranties\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LESI_TP_POO_27967 from the source code\&.
