.TH "trabalhoPOO_27967.Interface" 3 "Version v 1.0" "LESI_TP_POO_27967" \" -*- nroff -*-
.ad l
.nh
.SH NAME
trabalhoPOO_27967.Interface
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBIListManagement\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LESI_TP_POO_27967 from the source code\&.
