.TH "trabalhoPOO_27967.Categories" 3 "Version v 1.0" "LESI_TP_POO_27967" \" -*- nroff -*-
.ad l
.nh
.SH NAME
trabalhoPOO_27967.Categories \- Purpose:This file has the definition and methods to work with the plurality of Category\&. Created by: Jose Alves a27967 Created on: 11/14/2024 4:45:58 PM\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtrabalhoPOO_27967\&.Interface\&.IListManagement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCategories\fP ()"
.br
.RI "The default Constructor\&. "
.ti -1c
.RI "\fBCategories\fP (List< \fBCategory\fP > cats)"
.br
.RI "The constructor to use when a list of categories is given\&. "
.ti -1c
.RI "bool \fBAdd\fP (object obj)"
.br
.RI "Method used to add a category to a list of categories\&. "
.ti -1c
.RI "bool \fBRemove\fP (object obj)"
.br
.RI "Method used to remove a category from a list of categories\&. "
.ti -1c
.RI "bool \fBExist\fP (object obj)"
.br
.RI "Method used to verify if a category exists on a list of makes, given its ID or name\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "List< \fBCategory\fP > \fBCats\fP\fC [get, set]\fP"
.br
.RI "The property used to get and set the list of categories\&. "
.in -1c
.SH "Detailed Description"
.PP 
Purpose:This file has the definition and methods to work with the plurality of Category\&. Created by: Jose Alves a27967 Created on: 11/14/2024 4:45:58 PM\&. 


.PP
Definition at line \fB23\fP of file \fBCategories\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "trabalhoPOO_27967\&.Categories\&.Categories ()"

.PP
The default Constructor\&. 
.PP
Definition at line \fB36\fP of file \fBCategories\&.cs\fP\&.
.SS "trabalhoPOO_27967\&.Categories\&.Categories (List< \fBCategory\fP > cats)"

.PP
The constructor to use when a list of categories is given\&. 
.PP
\fBParameters\fP
.RS 4
\fIcats\fP 
.RE
.PP

.PP
Definition at line \fB45\fP of file \fBCategories\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool trabalhoPOO_27967\&.Categories\&.Add (object obj)"

.PP
Method used to add a category to a list of categories\&. 
.PP
\fBParameters\fP
.RS 4
\fIc\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Implements \fBtrabalhoPOO_27967\&.Interface\&.IListManagement\fP\&.
.PP
Definition at line \fB75\fP of file \fBCategories\&.cs\fP\&.
.SS "bool trabalhoPOO_27967\&.Categories\&.Exist (object obj)"

.PP
Method used to verify if a category exists on a list of makes, given its ID or name\&. 
.PP
\fBParameters\fP
.RS 4
\fIid\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP
If the ID is given
.PP
The Name is given
.PP
Implements \fBtrabalhoPOO_27967\&.Interface\&.IListManagement\fP\&.
.PP
Definition at line \fB109\fP of file \fBCategories\&.cs\fP\&.
.SS "bool trabalhoPOO_27967\&.Categories\&.Remove (object obj)"

.PP
Method used to remove a category from a list of categories\&. 
.PP
\fBParameters\fP
.RS 4
\fIc\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Implements \fBtrabalhoPOO_27967\&.Interface\&.IListManagement\fP\&.
.PP
Definition at line \fB91\fP of file \fBCategories\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "List<\fBCategory\fP> trabalhoPOO_27967\&.Categories\&.Cats\fC [get]\fP, \fC [set]\fP"

.PP
The property used to get and set the list of categories\&. 
.PP
Definition at line \fB57\fP of file \fBCategories\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LESI_TP_POO_27967 from the source code\&.
