.TH "trabalhoPOO_27967.Interface.IListManagement" 3 "Version v 1.0" "LESI_TP_POO_27967" \" -*- nroff -*-
.ad l
.nh
.SH NAME
trabalhoPOO_27967.Interface.IListManagement
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBtrabalhoPOO_27967\&.Campaigns\fP, \fBtrabalhoPOO_27967\&.Categories\fP, \fBtrabalhoPOO_27967\&.Clients\fP, \fBtrabalhoPOO_27967\&.Makes\fP, \fBtrabalhoPOO_27967\&.Products\fP, \fBtrabalhoPOO_27967\&.Sales\fP, and \fBtrabalhoPOO_27967\&.Warranties\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBAdd\fP (object obj)"
.br
.ti -1c
.RI "bool \fBRemove\fP (object obj)"
.br
.ti -1c
.RI "bool \fBExist\fP (object obj)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB17\fP of file \fBIListManagement\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool trabalhoPOO_27967\&.Interface\&.IListManagement\&.Add (object obj)"

.PP
Implemented in \fBtrabalhoPOO_27967\&.Campaigns\fP, \fBtrabalhoPOO_27967\&.Categories\fP, \fBtrabalhoPOO_27967\&.Clients\fP, \fBtrabalhoPOO_27967\&.Makes\fP, \fBtrabalhoPOO_27967\&.Products\fP, \fBtrabalhoPOO_27967\&.Sales\fP, and \fBtrabalhoPOO_27967\&.Warranties\fP\&.
.SS "bool trabalhoPOO_27967\&.Interface\&.IListManagement\&.Exist (object obj)"

.PP
Implemented in \fBtrabalhoPOO_27967\&.Campaigns\fP, \fBtrabalhoPOO_27967\&.Categories\fP, \fBtrabalhoPOO_27967\&.Clients\fP, \fBtrabalhoPOO_27967\&.Makes\fP, \fBtrabalhoPOO_27967\&.Products\fP, \fBtrabalhoPOO_27967\&.Sales\fP, and \fBtrabalhoPOO_27967\&.Warranties\fP\&.
.SS "bool trabalhoPOO_27967\&.Interface\&.IListManagement\&.Remove (object obj)"

.PP
Implemented in \fBtrabalhoPOO_27967\&.Campaigns\fP, \fBtrabalhoPOO_27967\&.Categories\fP, \fBtrabalhoPOO_27967\&.Clients\fP, \fBtrabalhoPOO_27967\&.Makes\fP, \fBtrabalhoPOO_27967\&.Products\fP, \fBtrabalhoPOO_27967\&.Sales\fP, and \fBtrabalhoPOO_27967\&.Warranties\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LESI_TP_POO_27967 from the source code\&.
