.TH "trabalhoPOO_27967.Campaigns" 3 "Version v 1.0" "LESI_TP_POO_27967" \" -*- nroff -*-
.ad l
.nh
.SH NAME
trabalhoPOO_27967.Campaigns \- Purpose:This file has the definition and methods to work with the plurality of Campaign\&. Created by: Jose Alves a27967 Created on: 11/14/2024 3:57:04 PM\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtrabalhoPOO_27967\&.Interface\&.IListManagement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCampaigns\fP ()"
.br
.RI "The default Constructor\&. "
.ti -1c
.RI "\fBCampaigns\fP (List< \fBCampaign\fP > p)"
.br
.RI "The constructor to use when a list of Campaigns is given\&. "
.ti -1c
.RI "bool \fBAdd\fP (object obj)"
.br
.RI "Method used to add a campaign to a list of campaigns\&. "
.ti -1c
.RI "bool \fBRemove\fP (object obj)"
.br
.RI "Method used to remove a campaign from a list of campaigns\&. "
.ti -1c
.RI "bool \fBExist\fP (object obj)"
.br
.RI "Method used to confirm if a campaign exists on a list of campaigns\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "List< \fBCampaign\fP > \fBCamps\fP\fC [get, set]\fP"
.br
.RI "Property used to get and set a Campaign list\&. "
.in -1c
.SH "Detailed Description"
.PP 
Purpose:This file has the definition and methods to work with the plurality of Campaign\&. Created by: Jose Alves a27967 Created on: 11/14/2024 3:57:04 PM\&. 


.PP
Definition at line \fB23\fP of file \fBCampaigns\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "trabalhoPOO_27967\&.Campaigns\&.Campaigns ()"

.PP
The default Constructor\&. 
.PP
Definition at line \fB36\fP of file \fBCampaigns\&.cs\fP\&.
.SS "trabalhoPOO_27967\&.Campaigns\&.Campaigns (List< \fBCampaign\fP > p)"

.PP
The constructor to use when a list of Campaigns is given\&. 
.PP
\fBParameters\fP
.RS 4
\fIp\fP 
.RE
.PP

.PP
Definition at line \fB45\fP of file \fBCampaigns\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool trabalhoPOO_27967\&.Campaigns\&.Add (object obj)"

.PP
Method used to add a campaign to a list of campaigns\&. 
.PP
\fBParameters\fP
.RS 4
\fIc\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Implements \fBtrabalhoPOO_27967\&.Interface\&.IListManagement\fP\&.
.PP
Definition at line \fB74\fP of file \fBCampaigns\&.cs\fP\&.
.SS "bool trabalhoPOO_27967\&.Campaigns\&.Exist (object obj)"

.PP
Method used to confirm if a campaign exists on a list of campaigns\&. 
.PP
\fBParameters\fP
.RS 4
\fIid\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Implements \fBtrabalhoPOO_27967\&.Interface\&.IListManagement\fP\&.
.PP
Definition at line \fB109\fP of file \fBCampaigns\&.cs\fP\&.
.SS "bool trabalhoPOO_27967\&.Campaigns\&.Remove (object obj)"

.PP
Method used to remove a campaign from a list of campaigns\&. 
.PP
\fBParameters\fP
.RS 4
\fIcamp\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Implements \fBtrabalhoPOO_27967\&.Interface\&.IListManagement\fP\&.
.PP
Definition at line \fB90\fP of file \fBCampaigns\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "List<\fBCampaign\fP> trabalhoPOO_27967\&.Campaigns\&.Camps\fC [get]\fP, \fC [set]\fP"

.PP
Property used to get and set a Campaign list\&. 
.PP
Definition at line \fB55\fP of file \fBCampaigns\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LESI_TP_POO_27967 from the source code\&.
