.TH "Category/Categories.cs" 3 "Version v 1.0" "LESI_TP_POO_27967" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Category/Categories.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtrabalhoPOO_27967\&.Categories\fP"
.br
.RI "Purpose:This file has the definition and methods to work with the plurality of Category\&. Created by: Jose Alves a27967 Created on: 11/14/2024 4:45:58 PM\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtrabalhoPOO_27967\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LESI_TP_POO_27967 from the source code\&.
