.TH "Make/Make.cs" 3 "Version v 1.0" "LESI_TP_POO_27967" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Make/Make.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtrabalhoPOO_27967\&.Make\fP"
.br
.RI "Purpose: Definition of Make and methods to deal with Make operations\&. Created by: Jose Alves a27967 Created on: 11/6/2024 11:22:09 AM\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtrabalhoPOO_27967\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LESI_TP_POO_27967 from the source code\&.
