.TH "trabalhoPOO_27967.Makes" 3 "Version v 1.0" "LESI_TP_POO_27967" \" -*- nroff -*-
.ad l
.nh
.SH NAME
trabalhoPOO_27967.Makes \- Purpose:This file has the definition and methods to work with the plurality of Make\&. Created by: Jose Alves a27967 Created on: 11/14/2024 4:33:51 PM\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMakes\fP ()"
.br
.RI "The default Constructor\&. "
.ti -1c
.RI "\fBMakes\fP (List< \fBMake\fP > m)"
.br
.RI "The constructor to use when a list of Make is given\&. "
.ti -1c
.RI "bool \fBAddMake\fP (\fBMake\fP m)"
.br
.RI "Method used to add a make to a list of makes\&. "
.ti -1c
.RI "bool \fBRemoveMake\fP (\fBMake\fP m)"
.br
.RI "Method used to remove a make from a list of makes\&. "
.ti -1c
.RI "bool \fBExistMake\fP (int id)"
.br
.RI "Method used to verify if a make exists on a list of makes, given its ID\&. "
.ti -1c
.RI "bool \fBExistMake\fP (string name)"
.br
.RI "Method used to verify if a make exists on a list of makes, given its name\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "List< \fBMake\fP > \fBMakeList\fP\fC [get, set]\fP"
.br
.RI "The property to get and set a list of Make\&. "
.in -1c
.SH "Detailed Description"
.PP 
Purpose:This file has the definition and methods to work with the plurality of Make\&. Created by: Jose Alves a27967 Created on: 11/14/2024 4:33:51 PM\&. 


.PP
Definition at line \fB21\fP of file \fBMakes\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "trabalhoPOO_27967\&.Makes\&.Makes ()"

.PP
The default Constructor\&. 
.PP
Definition at line \fB34\fP of file \fBMakes\&.cs\fP\&.
.SS "trabalhoPOO_27967\&.Makes\&.Makes (List< \fBMake\fP > m)"

.PP
The constructor to use when a list of Make is given\&. 
.PP
\fBParameters\fP
.RS 4
\fIm\fP 
.RE
.PP

.PP
Definition at line \fB43\fP of file \fBMakes\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool trabalhoPOO_27967\&.Makes\&.AddMake (\fBMake\fP m)"

.PP
Method used to add a make to a list of makes\&. 
.PP
\fBParameters\fP
.RS 4
\fIm\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB71\fP of file \fBMakes\&.cs\fP\&.
.SS "bool trabalhoPOO_27967\&.Makes\&.ExistMake (int id)"

.PP
Method used to verify if a make exists on a list of makes, given its ID\&. 
.PP
\fBParameters\fP
.RS 4
\fIid\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB101\fP of file \fBMakes\&.cs\fP\&.
.SS "bool trabalhoPOO_27967\&.Makes\&.ExistMake (string name)"

.PP
Method used to verify if a make exists on a list of makes, given its name\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB118\fP of file \fBMakes\&.cs\fP\&.
.SS "bool trabalhoPOO_27967\&.Makes\&.RemoveMake (\fBMake\fP m)"

.PP
Method used to remove a make from a list of makes\&. 
.PP
\fBParameters\fP
.RS 4
\fIm\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB83\fP of file \fBMakes\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "List<\fBMake\fP> trabalhoPOO_27967\&.Makes\&.MakeList\fC [get]\fP, \fC [set]\fP"

.PP
The property to get and set a list of Make\&. 
.PP
Definition at line \fB53\fP of file \fBMakes\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LESI_TP_POO_27967 from the source code\&.
