.TH "trabalhoPOO_27967.Categories" 3 "Version v 1.0" "LESI_TP_POO_27967" \" -*- nroff -*-
.ad l
.nh
.SH NAME
trabalhoPOO_27967.Categories \- Purpose:This file has the definition and methods to work with the plurality of Category\&. Created by: Jose Alves a27967 Created on: 11/14/2024 4:45:58 PM\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCategories\fP ()"
.br
.RI "The default Constructor\&. "
.ti -1c
.RI "\fBCategories\fP (List< \fBCategory\fP > cats)"
.br
.RI "The constructor to use when a list of categories is given\&. "
.ti -1c
.RI "bool \fBAddCategory\fP (\fBCategory\fP c)"
.br
.RI "Method used to add a category to a list of categories\&. "
.ti -1c
.RI "bool \fBRemoveCategory\fP (\fBCategory\fP c)"
.br
.RI "Method used to remove a category from a list of categories\&. "
.ti -1c
.RI "bool \fBExistCategory\fP (int id)"
.br
.RI "Method used to verify if a category exists on a list of makes, given its ID\&. "
.ti -1c
.RI "bool \fBExistCategory\fP (string name)"
.br
.RI "Method used to verify if a Category exists on a list of categories, given its name\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "List< \fBCategory\fP > \fBCats\fP\fC [get, set]\fP"
.br
.RI "The property used to get and set the list of categories\&. "
.in -1c
.SH "Detailed Description"
.PP 
Purpose:This file has the definition and methods to work with the plurality of Category\&. Created by: Jose Alves a27967 Created on: 11/14/2024 4:45:58 PM\&. 


.PP
Definition at line \fB21\fP of file \fBCategories\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "trabalhoPOO_27967\&.Categories\&.Categories ()"

.PP
The default Constructor\&. 
.PP
Definition at line \fB34\fP of file \fBCategories\&.cs\fP\&.
.SS "trabalhoPOO_27967\&.Categories\&.Categories (List< \fBCategory\fP > cats)"

.PP
The constructor to use when a list of categories is given\&. 
.PP
\fBParameters\fP
.RS 4
\fIcats\fP 
.RE
.PP

.PP
Definition at line \fB43\fP of file \fBCategories\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool trabalhoPOO_27967\&.Categories\&.AddCategory (\fBCategory\fP c)"

.PP
Method used to add a category to a list of categories\&. 
.PP
\fBParameters\fP
.RS 4
\fIc\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB73\fP of file \fBCategories\&.cs\fP\&.
.SS "bool trabalhoPOO_27967\&.Categories\&.ExistCategory (int id)"

.PP
Method used to verify if a category exists on a list of makes, given its ID\&. 
.PP
\fBParameters\fP
.RS 4
\fIid\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB103\fP of file \fBCategories\&.cs\fP\&.
.SS "bool trabalhoPOO_27967\&.Categories\&.ExistCategory (string name)"

.PP
Method used to verify if a Category exists on a list of categories, given its name\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB120\fP of file \fBCategories\&.cs\fP\&.
.SS "bool trabalhoPOO_27967\&.Categories\&.RemoveCategory (\fBCategory\fP c)"

.PP
Method used to remove a category from a list of categories\&. 
.PP
\fBParameters\fP
.RS 4
\fIc\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB85\fP of file \fBCategories\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "List<\fBCategory\fP> trabalhoPOO_27967\&.Categories\&.Cats\fC [get]\fP, \fC [set]\fP"

.PP
The property used to get and set the list of categories\&. 
.PP
Definition at line \fB55\fP of file \fBCategories\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LESI_TP_POO_27967 from the source code\&.
