.TH "trabalhoPOO_27967.Category" 3 "Version v 1.0" "LESI_TP_POO_27967" \" -*- nroff -*-
.ad l
.nh
.SH NAME
trabalhoPOO_27967.Category \- Purpose: Definition of Category and methods to deal with Category operations\&. Created by: Jose Alves a27967 Created on: 11/6/2024 11:20:47 AM\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCategory\fP ()"
.br
.RI "The default Constructor\&. "
.ti -1c
.RI "\fBCategory\fP (string name)"
.br
.RI "The constructor to use when the name of a category is given\&. "
.ti -1c
.RI "override bool \fBEquals\fP (object obj)"
.br
.RI "Method that overrides Equals() and verifies if a categry matches another one\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBoperator==\fP (\fBCategory\fP cat1, \fBCategory\fP cat2)"
.br
.RI "Redefinition of the Equal operator\&. "
.ti -1c
.RI "static bool \fBoperator!=\fP (\fBCategory\fP cat1, \fBCategory\fP cat2)"
.br
.RI "Redefinition of the Not Equal Operator\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP\fC [get, set]\fP"
.br
.RI "The property to get and set the ID of a category\&. "
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.RI "The property to get and set the name of a Category\&. "
.in -1c
.SH "Detailed Description"
.PP 
Purpose: Definition of Category and methods to deal with Category operations\&. Created by: Jose Alves a27967 Created on: 11/6/2024 11:20:47 AM\&. 


.PP
Definition at line \fB20\fP of file \fBCategory\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "trabalhoPOO_27967\&.Category\&.Category ()"

.PP
The default Constructor\&. 
.PP
Definition at line \fB35\fP of file \fBCategory\&.cs\fP\&.
.SS "trabalhoPOO_27967\&.Category\&.Category (string name)"

.PP
The constructor to use when the name of a category is given\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP 
.RE
.PP

.PP
Definition at line \fB45\fP of file \fBCategory\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool trabalhoPOO_27967\&.Category\&.Equals (object obj)"

.PP
Method that overrides Equals() and verifies if a categry matches another one\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP
Veriffies if the object given is null\&.
.PP
Casts the object to be Category\&.
.PP
Definition at line \fB81\fP of file \fBCategory\&.cs\fP\&.
.SS "static bool trabalhoPOO_27967\&.Category\&.operator!= (\fBCategory\fP cat1, \fBCategory\fP cat2)\fC [static]\fP"

.PP
Redefinition of the Not Equal Operator\&. 
.PP
\fBParameters\fP
.RS 4
\fIcat1\fP 
.br
\fIcat2\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB111\fP of file \fBCategory\&.cs\fP\&.
.SS "static bool trabalhoPOO_27967\&.Category\&.operator== (\fBCategory\fP cat1, \fBCategory\fP cat2)\fC [static]\fP"

.PP
Redefinition of the Equal operator\&. 
.PP
\fBParameters\fP
.RS 4
\fIcat1\fP 
.br
\fIcat2\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB100\fP of file \fBCategory\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int trabalhoPOO_27967\&.Category\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
The property to get and set the ID of a category\&. 
.PP
Definition at line \fB57\fP of file \fBCategory\&.cs\fP\&.
.SS "string trabalhoPOO_27967\&.Category\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
The property to get and set the name of a Category\&. 
.PP
Definition at line \fB66\fP of file \fBCategory\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LESI_TP_POO_27967 from the source code\&.
