.TH "trabalhoPOO_27967.Store" 3 "Version v 1.0" "LESI_TP_POO_27967" \" -*- nroff -*-
.ad l
.nh
.SH NAME
trabalhoPOO_27967.Store
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStore\fP"
.br
.RI "Purpose: This class has the definition and properties to manage a store\&. Created by: Jose Alves a27967 Created on: 11/14/2024 5:01:23 PM\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LESI_TP_POO_27967 from the source code\&.
